### ISSUE TITLE
`craniotomy_size` / implant possible mixup

### ISSUE THREAD

**Issue by bjhardcastle** [AllenNeuralDynamics/aind-metadata-service#89] opened 2023-03-29 23:00 UTC
- trying to access the implant type for `subject: 623322` (Mindscope Dynamic Routing project)
- the expected value from `Implant ID/Coverslip type` column in SharePoint appears under the field `craniotomy_size`, formatted as a float instead of a string
- the behavior isn't unique to this subject or implant type (for subjects under the same project)

Got (from [http://aind-metadata-service/procedures/623322](http://aind-metadata-service/procedures/623322)):
```
"craniotomy_size" : -4.0,
```
Expected:
A field with an appropriate label and a string value:
```
implant_id_coverslip_type: "TS-4.0",
```

Seems to be caused by this line ([aind_metadata_service.sharepoint.client L1237](https://github.com/AllenNeuralDynamics/aind-metadata-service/blob/main/src/aind_metadata_service/sharepoint/client.py#L1237L1239)):
```python
craniotomy_size = parse_str_into_float(
    list_item.get_property(list_fields.IMPLANT_ID_COVERSLIP_TYPE.value)
)
```

**Comment by mekhlakapoor** [comment] 2023-04-11 21:54
This is because the SWR does not actually keep track of craniotomy size but that information can be parsed from the Implant ID/Coverslip Type column. I don't think Implant type is currently being tracked in aind-data-schema but @saskiad @bjhardcastle correct me if that's there/a field of interest

**Comment by mekhlakapoor** [comment] 2023-04-13 17:15
craniotomy_size = parse_str_into_float(
    list_item.get_property(list_fields.CRANIOTOMY_TYPE.value)
)

**Comment by bjhardcastle** [comment] 2023-04-17 17:34
@mekhlakapoor I would certainly make use of "Implant ID/Coverslip Type" (str) if made available via an additional field

**Comment by mekhlakapoor** [comment] 2023-04-17 21:32
@bjhardcastle  so to clarify you're interested in having an additional field in aind-data-schema to track Implant ID/Coverslip Type correct? I'll go ahead and create a feature request for that in that repo, and close this issue once confirmed.

**Comment by bjhardcastle** [comment] 2023-04-17 21:39
> @bjhardcastle so to clarify you're interested in having an additional field in aind-data-schema to track Implant ID/Coverslip Type correct? I'll go ahead and create a feature request for that in that repo, and close this issue once confirmed.

That's correct. Thanks!

**Closed** 2023-04-17 21:51 UTC
